.catalog:
  name: "[Galaxyians] Galaxy"
  version: "1.0.0"
  description: "CTF Galaxy Instance"
  questions:

galaxy:
  scale: 1
  health_check:
    port: 80
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
