version: '2'
services:
  ctfd:
    image: quay.io/galaxy-ctf/ctfd:gcc2017
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root@db/ctfd
      CTFD_YAML_FILE: /data.yml
    volumes:
      - .data/CTFd/logs:/opt/CTFd/CTFd/logs
    links:
      - db:db
    labels:
      io.rancher.sidekicks: db
      io.rancher.scheduler.affinity:host_label_soft: role=compute
  db:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .data/mysql:/var/lib/mysql
