.catalog:
  name: "CTFd"
  version: "1.0.0"
  description: "CTF Scorebaord"
  questions:

ctfd:
  scale: 1
  health_check:
    port: 8000
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
